export const theme = {
  colors: {
    primary: '#A67168',
    primaryLight: '#CDA09B',
    primaryDark: '#8B5A50',
    secondary: '#F4E8E6',
    white: '#FFFFFF',
    lightGray: '#F5F5F5',
    gray: '#757575',
    darkGray: '#212121',
    text: '#1A1A1A',
    textSecondary: '#6B6B6B',
    error: '#FF4C4C',
    success: '#A67168',
    border: '#E5E7EB',
    background: '#FAFAFA',
    card: '#FFFFFF',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  shadow: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 4,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 16,
      elevation: 8,
    },
  },
};
