spring.application.name=innova
server.port=8080

# SQL Server Somee (Remoto)
spring.datasource.url=jdbc:sqlserver://innova_solutions.mssql.somee.com:1433;databaseName=innova_solutions;encrypt=false;trustServerCertificate=true
spring.datasource.username=innova
spring.datasource.password=innova-solutions
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true